mj:
  discord:
    bot-token: xxx #机器人token
    guild-id: xxx #服务器id
    channel-id: xxx  #频道id
    user-token: xxx  #用户token
    session-id: xxx
    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
    user-wss: true
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: null
  queue:
    timeout-minutes: 15
    core-size: 10
    queue-size: 30
  mengWang:
    smApiKey: xxx
    phone: xxx

